[package]
name = "kapra_chain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha3 = "0.10.8"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
log = "0.4"
pretty_assertions = "1.3"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
wasmtime = "1.0"
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = "1.0"
seccompiler = "0.3"
serde_json = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
walkdir = "2.3"
tempfile = "3.8"

# BLS12-381 signature lib
blst = "0.3"

# Post-quantum Dilithium support (via PQClean)
pqcrypto-dilithium = { version = "0.7", features = ["dilithium5"] }
