// lib.rs
mod ksl_ast;
mod ksl_parser;
mod ksl_checker;
mod ksl_compiler;
mod ksl_llvm;
mod ksl_errors;
pub mod ksl_scaffold;
pub mod scaffold_lint;
pub mod gas_profile;
pub mod ksl_smart_account;
pub mod ksl_ir;
pub mod ksl_abi;
pub mod ksl_lsp;
pub mod ksl_types;
pub mod ksl_stdlib_crypto;
pub mod ksl_syscalls;
pub mod ksl_validator_contract;
mod ksl_package;
mod ksl_version;
mod ksl_export;
mod ksl_stdlib;
pub mod ksl_macros;
pub mod ksl_generics;
pub mod ksl_analyzer;
pub mod ksl_bytecode;
pub mod ksl_wasm;
pub mod ksl_irgen;
pub mod ksl_async;

// Added missing module declarations - assuming these files exist in src/
pub mod ksl_kapra_crypto;
pub mod kapra_vm; // Or ksl_vm, needs confirmation of filename
pub mod ksl_linter;
pub mod ksl_docgen;
pub mod ksl_kapra_zkp;
pub mod ksl_value;
pub mod ksl_module;
pub mod ksl_validator_keys;
pub mod ksl_contract;
pub mod ksl_ast_transform;

pub use ksl_ast::*;
pub use ksl_parser::*;
pub use ksl_checker::*;
pub use ksl_compiler::*;
pub use ksl_llvm::*;
pub use ksl_errors::*;
pub use ksl_lsp::*;
pub use ksl_macros::*;
pub use ksl_generics::*;
pub use ksl_analyzer::*;
pub use ksl_bytecode::*;
pub use ksl_wasm::*;
pub use ksl_irgen::*;
pub use ksl_types::*;
pub use ksl_stdlib_crypto::*;
pub use ksl_syscalls::*;
pub use ksl_async::*;

// Added pub use for new modules
pub use ksl_kapra_crypto::*;
pub use kapra_vm::*; // Or ksl_vm
pub use ksl_linter::*;
pub use ksl_docgen::*;
pub use ksl_kapra_zkp::*;
pub use ksl_value::*;
pub use ksl_module::*;
pub use ksl_validator_keys::*;
pub use ksl_contract::*;
pub use ksl_ast_transform::*;

// Added pub mod for missing files
pub mod ksl_benchmark;
pub mod ksl_config;
pub mod ksl_contract_verifier;
pub mod ksl_deploy;
pub mod ksl_hot_reload;
pub mod ksl_stdlib_math;
pub mod ksl_stdlib_net;
pub mod ksl_repl_server;
pub mod ksl_refactor;
pub mod ksl_repl;
pub mod ksl_simulator;
pub mod ksl_verifier;
pub mod ksl_plugins;
pub mod ksl_jit;
pub mod ksl_typegen;
pub mod ksl_updater;
pub mod ksl_web3;
pub mod ksl_vscode;
pub mod ksl_stdlib_io;
pub mod ksl_kapra_consensus;
pub mod ksl_kapra_shard;
pub mod ksl_kapra_validator;
pub mod ksl_metrics;
pub mod ksl_package_version;
pub mod ksl_bundler;
pub mod ksl_cli;
pub mod ksl_coverage;
pub mod ksl_debug;
pub mod ksl_dev_tools;
pub mod ksl_doc_lsp;
pub mod ksl_fuzzer;
pub mod ksl_game;
pub mod ksl_interpreter;
pub mod ksl_genesis;
pub mod ksl_doc;
pub mod ksl_data_blob;
pub mod ksl_test;
pub mod ksl_scaffold_gui;
pub mod ksl_aot;
pub mod ksl_sandbox;
pub mod ksl_bench;
pub mod ksl_package_publish;
pub mod ksl_ci;
pub mod ksl_cli_spec;
pub mod ksl_kapra_scheduler;
pub mod ksl_optimizer;
pub mod ksl_iot;
pub mod ksl_embedded;
pub mod ksl_community;
pub mod ksl_dep_audit;
pub mod ksl_runtime_monitor;
pub mod ksl_migrate;
pub mod ksl_template;
pub mod ksl_project;
pub mod ksl_transpiler;
pub mod ksl_testgen;
pub mod ksl_profile;
pub mod ksl_security;
pub mod ksl_package;
pub use ksl_benchmark::*;
pub use ksl_config::*;
pub use ksl_contract_verifier::*;
pub use ksl_deploy::*;
pub use ksl_hot_reload::*;
pub use ksl_stdlib_math::*;
pub use ksl_stdlib_net::*;
pub use ksl_repl_server::*;
pub use ksl_refactor::*;
pub use ksl_repl::*;
pub use ksl_simulator::*;
pub use ksl_verifier::*;
pub use ksl_plugins::*;
pub use ksl_jit::*;
pub use ksl_typegen::*;
pub use ksl_updater::*;
pub use ksl_web3::*;
pub use ksl_vscode::*;
pub use ksl_stdlib_io::*;
pub use ksl_kapra_consensus::*;
pub use ksl_kapra_shard::*;
pub use ksl_kapra_validator::*;
pub use ksl_metrics::*;
pub use ksl_package_version::*;
pub use ksl_bundler::*;
pub use ksl_cli::*;
pub use ksl_coverage::*;
pub use ksl_debug::*;
pub use ksl_dev_tools::*;
pub use ksl_doc_lsp::*;
pub use ksl_fuzzer::*;
pub use ksl_game::*;
pub use ksl_interpreter::*;
pub use ksl_genesis::*;
pub use ksl_doc::*;
pub use ksl_data_blob::*;
pub use ksl_test::*;
pub use ksl_scaffold_gui::*;
pub use ksl_aot::*;
pub use ksl_sandbox::*;
pub use ksl_bench::*;
pub use ksl_package_publish::*;
pub use ksl_ci::*;
pub use ksl_cli_spec::*;
pub use ksl_kapra_scheduler::*;
pub use ksl_optimizer::*;
pub use ksl_iot::*;
pub use ksl_embedded::*;
pub use ksl_community::*;
pub use ksl_dep_audit::*;
pub use ksl_runtime_monitor::*;
pub use ksl_migrate::*;
pub use ksl_template::*;
pub use ksl_project::*;
pub use ksl_transpiler::*;
pub use ksl_testgen::*;
pub use ksl_profile::*;
pub use ksl_security::*;
pub use ksl_package::*;
pub use scaffold_lint::*;
pub use gas_profile::*;
pub use ksl_stdlib::*; 